# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0014_facts'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetupModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(default='', max_length=200, unique=True)),
                ('groups', models.ManyToManyField(to='inventory.Group')),
                ('hosts', models.ManyToManyField(to='inventory.Host')),
            ],
        ),
    ]
