# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setupmodule',
            name='command',
            field=models.CharField(default='123', max_length=200, unique=True),
        ),
    ]
