# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-04 02:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20160203_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groupvar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('var_name', models.CharField(max_length=200)),
                ('var_value', models.CharField(max_length=200)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Group')),
            ],
        ),
        migrations.RenameModel(
            old_name='Var',
            new_name='Hostvar',
        ),
        migrations.RemoveField(
            model_name='host',
            name='pub_date',
        ),
    ]
