# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-04 04:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20160204_0228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groupchild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ansible_group', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Hostchild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ansible_alias', models.CharField(max_length=200)),
                ('Host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Host')),
            ],
        ),
        migrations.RemoveField(
            model_name='group',
            name='ansible_children',
        ),
        migrations.AddField(
            model_name='groupchild',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Group'),
        ),
    ]
