# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-05 01:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20160204_0412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostchild',
            name='Host',
        ),
        migrations.RemoveField(
            model_name='groupchild',
            name='ansible_group',
        ),
        migrations.AlterField(
            model_name='groupchild',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.Group'),
        ),
        migrations.DeleteModel(
            name='Hostchild',
        ),
    ]
