# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-05 03:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20160205_0159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groupchildren',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('children', models.ManyToManyField(to='inventory.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Groupchildrenrel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.Group')),
                ('group_children', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.Groupchildren')),
            ],
        ),
        migrations.RemoveField(
            model_name='groupchild',
            name='group',
        ),
        migrations.DeleteModel(
            name='Groupchild',
        ),
    ]
