# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-06 12:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20160205_0329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupchildrenrel',
            name='group_children',
        ),
        migrations.AddField(
            model_name='groupchildren',
            name='groupchildren_rel',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='inventory.Groupchildrenrel'),
            preserve_default=False,
        ),
    ]
