# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-06 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_auto_20160206_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupchildren',
            name='children',
        ),
        migrations.RemoveField(
            model_name='groupchildren',
            name='groupchildren_rel',
        ),
        migrations.RemoveField(
            model_name='groupchildrenrel',
            name='group',
        ),
        migrations.AddField(
            model_name='group',
            name='ansible_children',
            field=models.ManyToManyField(related_name='_group_ansible_children_+', to='inventory.Group'),
        ),
        migrations.DeleteModel(
            name='Groupchildren',
        ),
        migrations.DeleteModel(
            name='Groupchildrenrel',
        ),
    ]
