# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-06 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_auto_20160206_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='ansible_group',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='ansible_alias',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
