# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-03 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ansible_children', models.TextField(default='')),
                ('ansible_vars', models.TextField(default='')),
            ],
        ),
        migrations.RemoveField(
            model_name='host',
            name='ansible_host',
        ),
        migrations.RemoveField(
            model_name='host',
            name='ansible_port',
        ),
        migrations.RemoveField(
            model_name='host',
            name='ansible_user',
        ),
        migrations.AddField(
            model_name='host',
            name='ansible_vars',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='group',
            name='ansible_hosts',
            field=models.ManyToManyField(to='inventory.Host'),
        ),
    ]
