# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-03 13:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20160203_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Var',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('var_name', models.CharField(max_length=200)),
                ('var_value', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='group',
            name='ansible_vars',
        ),
        migrations.RemoveField(
            model_name='host',
            name='ansible_vars',
        ),
        migrations.AddField(
            model_name='var',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Host'),
        ),
    ]
